### ISSUE TITLE
Is it better to use Object.keys ?

### ISSUE THREAD

**Issue by jerrybendy** [jonschlinkert/object-length#1]
I don't sure is it will be better ?

``` js
var obj = {a: 1, b: 2, c: 3};

console.log(Object.keys(obj).length);
```

`Object.keys` will return an array with all keys of object besides of inherits. So we can use `Object.keys(obj).length)` to get the length of object.

**Comment by jonschlinkert** [comment]
They're basically the same, but the current method is faster.
